### ISSUE TITLE
feat: add plugins list at build

### ISSUE THREAD

**Issue by tristanrobert** [MTES-MCT/mattermost-buildpack#3]

**Comment by tristanrobert** [comment]
Par exemple lister les repos dans `MATTERMOST_PLUGINS=github: owner1/repo1,owner2/repo2`

**Comment by jdauphant** [comment]
https://api.integrations.mattermost.com/api/v1/plugins

**Comment by jdauphant** [comment]
Client : https://github.com/mattermost/mattermost-server/blob/dfa476a6882373ba73b429fd9d9ea796de28bd41/services/marketplace/client.go

**Comment by tristanrobert** [comment]
@jdauphant tous les plugins ne sont pas dans le marketplace, par exemple [BigBlueButton](https://github.com/blindsidenetworks/mattermost-plugin-bigbluebutton/blob/master/README.md#installation-and-setup). Il peut alors être intéressant d'aller chercher aussi dans github. Autre difficulté, l'installation consistant à décompresser l'archive du binaire est déconseillée, notamment parce que certains plugins sont plus complexes et ajoutent de l'UI (zoom) en plus d'ajouter des [fonctions serveur](https://docs.mattermost.com/administration/plugins.html#about-plugins). En passant par la commande mattermost, celle ci lit leur manifest et détermine le mode d'installation complet. Deux solutions: soit les installer dans prepackaged sinon utiliser la commande mattermost pour les installer en [post deploy](https://doc.scalingo.com/platform/app/postdeploy-hook)

**Comment by tristanrobert** [comment]
Résultats des tests: 

- copier les plugins dans le dossier `prepackaged_plugins` les rends installables par l'interface mais impossible de les installer car ils ne sont pas signés
- copier dans un répertoire `postdeploy_plugins` puis lancer un postdeploy dessus fonctionne !!!

**Comment by tristanrobert** [comment]
-
