### ISSUE TITLE
feat: config in database

### ISSUE THREAD

**Issue by jdauphant** [MTES-MCT/mattermost-buildpack#4]
Currently configuration made in System Console is lost at each start and upgrade.
"Mattermost must have write permissions to config.json, otherwise changes made in the System Console will have no effect." ->

Suggestion : implement : https://docs.mattermost.com/administration/config-in-database.html

**Comment by jdauphant** [comment]
MM_CONFIG=$SCALINGO_POSTGRESQL_URL should be enough

**Comment by tristanrobert** [comment]
En fait il faut utiliser `MM_CONFIG=$SCALINGO_POSTGRESQL_URL`, car l'appel d'une variable contenant une variable comme `DATABASE_URL` ne fonctionne pas.

**Comment by tristanrobert** [comment]
Fixed in PR https://github.com/MTES-MCT/mattermost-buildpack/pull/6
